//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jointly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jointly.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Authorization_Email {
            get {
                return ResourceManager.GetString("Authorization_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string Authorization_Error {
            get {
                return ResourceManager.GetString("Authorization_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist! Try another address and phone!.
        /// </summary>
        internal static string Authorization_Exist {
            get {
                return ResourceManager.GetString("Authorization_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Authorization_Login {
            get {
                return ResourceManager.GetString("Authorization_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Authorization_Password {
            get {
                return ResourceManager.GetString("Authorization_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Authorization_Phone {
            get {
                return ResourceManager.GetString("Authorization_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Authorization_SignIn {
            get {
                return ResourceManager.GetString("Authorization_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Authorization_SignUp {
            get {
                return ResourceManager.GetString("Authorization_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email for confirmation message!.
        /// </summary>
        internal static string Authorization_Success {
            get {
                return ResourceManager.GetString("Authorization_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Authorization_Username {
            get {
                return ResourceManager.GetString("Authorization_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        internal static string CreateEvent_Address {
            get {
                return ResourceManager.GetString("CreateEvent_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string CreateEvent_Create {
            get {
                return ResourceManager.GetString("CreateEvent_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string CreateEvent_Date {
            get {
                return ResourceManager.GetString("CreateEvent_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string CreateEvent_Description {
            get {
                return ResourceManager.GetString("CreateEvent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END.
        /// </summary>
        internal static string CreateEvent_EndTime {
            get {
                return ResourceManager.GetString("CreateEvent_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string CreateEvent_Name {
            get {
                return ResourceManager.GetString("CreateEvent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string CreateEvent_StartTime {
            get {
                return ResourceManager.GetString("CreateEvent_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create event.
        /// </summary>
        internal static string CreateEvent_Title {
            get {
                return ResourceManager.GetString("CreateEvent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct email.
        /// </summary>
        internal static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter login.
        /// </summary>
        internal static string Error_Login {
            get {
                return ResourceManager.GetString("Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string Error_Password {
            get {
                return ResourceManager.GetString("Error_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct phone.
        /// </summary>
        internal static string Error_Phone {
            get {
                return ResourceManager.GetString("Error_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct username.
        /// </summary>
        internal static string Error_Username {
            get {
                return ResourceManager.GetString("Error_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        internal static string Profile_ConfirmPassword {
            get {
                return ResourceManager.GetString("Profile_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTIFICATIONS.
        /// </summary>
        internal static string Profile_Notifications {
            get {
                return ResourceManager.GetString("Profile_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New events close to me.
        /// </summary>
        internal static string Profile_Notifications_NewEvents {
            get {
                return ResourceManager.GetString("Profile_Notifications_NewEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        internal static string Profile_Password {
            get {
                return ResourceManager.GetString("Profile_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        internal static string Profile_Phone {
            get {
                return ResourceManager.GetString("Profile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your events.
        /// </summary>
        internal static string SavedEvents_Title {
            get {
                return ResourceManager.GetString("SavedEvents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SignUp_Agreement {
            get {
                return ResourceManager.GetString("SignUp_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUp_Button {
            get {
                return ResourceManager.GetString("SignUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST NAME.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST NAME.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        internal static string SignUp_Password_Confirm {
            get {
                return ResourceManager.GetString("SignUp_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
